# Generated by Django 5.2.5 on 2025-09-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qtext', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=50)),
                ('op1', models.CharField(max_length=50)),
                ('op2', models.CharField(max_length=50)),
                ('op3', models.CharField(max_length=50)),
                ('op4', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=70)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'result',
            },
        ),
    ]
